Added: simple helm chart - deployment per node
***What does this change do?***

- Added simple helm chart - as a statefulset

***Why is this change needed?***

- Extract the kubernetes manifests into a collection of manifests

- Use helm due to the templating capabilities which are currently
required.

diff --git a/create-kube-network b/create-kube-network
--- a/create-kube-network
+++ b/create-kube-network
@@ -1,29 +1,26 @@
 #!/bin/bash
 source ./shflags
 
-docker_repository="878804750492.dkr.ecr.us-east-2.amazonaws.com"
 build_bucket="builds.casperlabs.io"
 
 kibana_filebeat_index="32f407c0-9755-11eb-9976-1debcb3b57c8"
 kibana_host="kibana.test.k8s.casperlabs.io"
-
-# ./create-kube-network --network_name_prefix "$(whoami)"
-#                      --node_count 10 \
-#                      --node_cpu 2 \
-#                      --node_mem 2Gi \
-#                      --node_storage 10Gi \
-#                      --genesis_in_seconds 300
 
 ############################################################################################
 # opts
 ############################################################################################
 
 
-DEFINE_string 'network_name_prefix' '' 'network_name_prefix' 'n'
+DEFINE_string 'image_tag' 'latest' 'image_tag' 'i'
+DEFINE_string 'network_name_prefix' '' 'network_name_prefix' 'p'
+DEFINE_string 'node_name_prefix' 'casper-node' 'node name' 'n'
 DEFINE_string 'node_count' '5' 'node count' 't'
+DEFINE_string 'bootstrap_node_count' '1' 'bootstrap node count' 'b'
+DEFINE_string 'validator_node_count' '2' 'bootstrap node count' 'v'
+DEFINE_string 'zero_weight_node_count' '2' 'bootstrap node count' 'z'
 DEFINE_string 'node_cpu' '500m' 'node cpu request' 'c'
 DEFINE_string 'node_mem' '500Mi' 'node memory request' 'm'
-DEFINE_string 'node_storage' '1Gi' 'node storage volume size' 's'
+DEFINE_string 'node_storage_capacity' '1Gi' 'node storage volume size' 's'
 DEFINE_string 'genesis_in_seconds' '300' 'genesis start x seconds in the future' 'g'
 
 # Parse the command-line.
@@ -34,20 +31,34 @@ echo "--------------------------------------------------"
 echo "opts"
 echo "--------------------------------------------------"
 
+echo "image_tag: ${FLAGS_image_tag}"
 echo "network_name_prefix: ${FLAGS_network_name_prefix}"
+echo "node_name_prefix: ${FLAGS_node_name_prefix}"
 echo "node_count: ${FLAGS_node_count}"
+echo "bootstrap_node_count: ${FLAGS_bootstrap_node_count}"
+echo "validator_node_count: ${FLAGS_validator_node_count}"
+echo "zero_weight_node_count ${FLAGS_zero_weight_node_count}"
 echo "node_cpu: ${FLAGS_node_cpu}"
 echo "node_mem: ${FLAGS_node_mem}"
-echo "node_storage: ${FLAGS_node_storage}"
+echo "node_storage_capacity: ${FLAGS_node_storage_capacity}"
 echo "genesis_in_seconds: ${FLAGS_genesis_in_seconds}"
 
-network_name_prefix=$FLAGS_network_name_prefix
+image_tag=$FLAGS_image_tag
+if [[ -z "${FLAGS_network_name_prefix}" ]]; then
+  network_name_prefix="$(whoami)"
+else
+  network_name_prefix="${FLAGS_network_name_prefix}"
+fi
+node_name_prefix=$FLAGS_node_name_prefix
 node_count=$FLAGS_node_count
+bootstrap_node_count=$FLAGS_bootstrap_node_count
+validator_node_count=$FLAGS_validator_node_count
+zero_weight_node_count=$FLAGS_zero_weight_node_count
 node_mem_limit=$FLAGS_node_mem
 node_mem_request=$FLAGS_node_mem
 node_cpu_limit=$FLAGS_node_cpu
 node_cpu_request=$FLAGS_node_cpu
-node_storage=$FLAGS_node_storage
+node_storage_capacity=$FLAGS_node_storage_capacity
 genesis_in_seconds=$FLAGS_genesis_in_seconds
 
 ############################################################################################
@@ -112,13 +123,36 @@ fi
 # uniquely name network
 ############################################################################################
 
+function get_network_prefix() {
+  if [[ -z "${network_name_prefix}" ]]; then
+    whoami
+  else
+    echo "${network_name_prefix}"
+  fi
+}
 
-git_hash=`cd ../casper-node/; git rev-parse --short HEAD`
-if [[ -z "${network_name_prefix}" ]]; then
-  network_name_prefix=`whoami`
-fi
-random=`openssl rand -hex 2`
-network_name="${network_name_prefix}-${git_hash}-${random}"
+function get_git_hash() {
+  local casper_node_git_hash
+
+  if [[ -d ../casper-node ]]; then
+    (pushd ../casper-node/ || exit) > /dev/null 2>&1
+  else
+    >&2 echo "The casper-node directory seems to be missing"
+    exit 1
+  fi
+  casper_node_git_hash="$(git rev-parse --short HEAD)"
+  (popd || exit) > /dev/null 2>&1
+  echo "${casper_node_git_hash}"
+}
+
+function get_network_suffix() {
+  openssl rand -hex 2
+}
+
+network_prefix="$(get_network_prefix)"
+git_hash="$(get_git_hash)"
+network_suffix="$(get_network_suffix)"
+network_name="${network_prefix}-${git_hash}-${network_suffix}"
 
 if [[ "$( kubectl get namespaces | grep -c "${network_name}")" -gt 0 ]]; then
   >&2 echo "There is already a namespace for the given network_name_prefix"
@@ -130,13 +164,138 @@ fi
 # generate casper-tool artifacts
 ############################################################################################
 
+function generate_hosts_file() {
+  local node_name_prefix="${1:-casper-node}"
+  local nodes="${2:-5}"
+  local bootstrap_nodes="${3}"
+  local validator_nodes="${4}"
+  local zero_weight_nodes="${5}"
+  local remaining_nodes
+  local calculated_sum_of_nodes
+
+  if [[ -z "${bootstrap_nodes}" ]]; then
+    echo "Setting the number of bootstrap_nodes to default of 1"
+    bootstrap_nodes=1
+  fi
+
+  local remaining_nodes="$(("${nodes}"-"${bootstrap_nodes}"))"
+
+  if [[ -z "${validator_nodes}" ]]; then
+    local default_validator_nodes
+    default_validator_nodes="$(("${remaining_nodes}"/2))"
+    echo "Setting the number of validator_nodes to default of ${default_validator_nodes}"
+    validator_nodes="${default_validator_nodes}"
+  fi
+
+  local remaining_nodes="$(("${nodes}"-"${validator_nodes}"-"${bootstrap_nodes}"))"
+
+  if [[ -z "${zero_weight_nodes}" ]]; then
+    zero_weight_nodes="${remaining_nodes}"
+  fi
+
+  calculated_sum_of_nodes="$(("${zero_weight_nodes}"+"${validator_nodes}"+"${bootstrap_nodes}"))"
+
+  if [[ "${nodes}" != "${calculated_sum_of_nodes}" ]]; then
+    >&2 echo "The total number of nodes must be equal to the calculated sum of nodes"
+    exit 1
+  fi
+
+  cp "${PWD}"/kube-hosts.yaml.tpl "${PWD}"/kube-hosts.yaml
+
+  local bootstrap_nodes_sequence_step
+  local validator_nodes_sequence_step
+  local zero_weight_sequence_step
+  bootstrap_nodes_sequence_step="$(("${bootstrap_nodes}"-1))"
+  validator_nodes_sequence_step="$(("${bootstrap_nodes_sequence_step}"+"${validator_nodes}"))"
+  zero_weight_sequence_step="$(("${validator_nodes_sequence_step}"+"${zero_weight_nodes}"))"
+
+  local bootstrap_node_type_args
+  local validator_node_type_args
+  local zero_weight_node_type_args
+  local bootstrap_node_kv_args
+  local validator_node_kv_args
+  local zero_weight_node_kv_args
+
+  for node_index in $(seq 0 "${bootstrap_nodes_sequence_step}"); do
+    bootstrap_node_type_args="${bootstrap_node_type_args} -t string"
+    bootstrap_node_kv_args="${bootstrap_node_kv_args} ${node_name_prefix}-${node_index}="
+  done
+
+  # shellcheck disable=2086
+  dasel put object \
+    -f "${PWD}"/kube-hosts.yaml \
+    ${bootstrap_node_type_args} \
+    -s "all.children.bootstrap.hosts" \
+    ${bootstrap_node_kv_args}
+
+  for node_index in $(seq "$((bootstrap_nodes_sequence_step+1))" "${validator_nodes_sequence_step}"); do
+    validator_node_type_args="${validator_node_type_args} -t string"
+    validator_node_kv_args="${validator_node_kv_args} ${node_name_prefix}-${node_index}="
+  done
+
+  # shellcheck disable=2086
+  dasel put object \
+    -f "${PWD}"/kube-hosts.yaml \
+    ${validator_node_type_args} \
+    -s "all.children.validators.hosts" \
+    ${validator_node_kv_args}
+
+  for node_index in $(seq "$((validator_nodes_sequence_step+1))" "${zero_weight_sequence_step}"); do
+    zero_weight_node_type_args="${zero_weight_node_type_args} -t string"
+    zero_weight_node_kv_args="${zero_weight_node_kv_args} ${node_name_prefix}-${node_index}="
+  done
+
+  # shellcheck disable=2086
+  dasel put object \
+    -f "${PWD}"/kube-hosts.yaml \
+    ${zero_weight_node_type_args} \
+    -s "all.children.zero_weight.hosts" \
+    ${zero_weight_node_kv_args}
+}
+
+
+echo "--------------------------------------------------"
+echo "Generating kube-hosts.yaml file"
+echo """
+generate_hosts_file \\
+  \$node_name_prefix \\
+  \$node_count \\
+  \$bootstrap_node_count \\
+  \$validator_node_count \\
+  \$zero_weight_node_count
+generate_hosts_file \
+  $node_name_prefix \
+  $node_count \
+  $bootstrap_node_count \
+  $validator_node_count \
+  $zero_weight_node_count
+"""
+
+generate_hosts_file \
+  "${node_name_prefix}" \
+  "${node_count}" \
+  "${bootstrap_node_count}" \
+  "${validator_node_count}" \
+  "${zero_weight_node_count}"
+
+echo "--------------------------------------------------"
+echo "Displaying the generated kube-hosts.yaml file"
+cat "${PWD}"/kube-hosts.yaml
+
 echo "--------------------------------------------------"
 echo "running casper-tool:"
-echo "./casper-tool.py create-network --genesis-in $genesis_in_seconds --hosts-file kube-hosts.yaml artifacts/$network_name"
+echo """
+./casper-tool.py create-network
+  --genesis-in $genesis_in_seconds
+  --hosts-file kube-hosts.yaml
+  artifacts/$network_name
+"""
 echo "--------------------------------------------------"
 
-./casper-tool.py create-network --genesis-in $genesis_in_seconds --hosts-file kube-hosts.yaml artifacts/$network_name
-
+./casper-tool.py create-network \
+  --genesis-in "${genesis_in_seconds}" \
+  --hosts-file kube-hosts.yaml \
+  artifacts/"${network_name}"
 
 ############################################################################################
 # generate stests network artifacts
@@ -182,9 +341,6 @@ aws s3 sync artifacts/$network_name s3://$build_bucket/networks/$network_name
 # create Kubernetes Resources
 ############################################################################################
 
-
-kube_resources_yaml="./artifacts/${network_name}/kube_resources.yaml"
-
 echo "--------------------------------------------------"
 echo "Creating network in kube namespace $network_name"
 echo "--------------------------------------------------"
@@ -192,152 +348,25 @@ echo ""
 echo "Network Name: $network_name"
 echo "Build git rev: $git_hash"
 echo ""
-echo "writing $kube_resources_yaml"
 
-for index in $(seq 1 $node_count)
-do
+kubectl create namespace "$network_name" || true
 
-zero_pad_index=$(printf %03d $index)
-node_label="casper-node-$zero_pad_index"
-
-cat << EOF >> $kube_resources_yaml
-#
-# $node_label
-#
-
----
-apiVersion: v1
-kind: PersistentVolumeClaim
-metadata:
-  name: $node_label-pv-claim
-spec:
-  storageClassName: gp2
-  accessModes:
-    - ReadWriteOnce
-  resources:
-    requests:
-      storage: $node_storage
-
----
-kind: Service
-apiVersion: v1
-metadata:
-  name: $node_label
-spec:
-  selector:
-    app: $node_label
-  ports:
-    - name: rest
-      protocol: TCP
-      port: 8888
-      targetPort: 8888
-    - name: rpc
-      protocol: TCP
-      port: 7777
-      targetPort: 7777
-    - name: casper-node
-      protocol: TCP
-      port: 34553
-      targetPort: 34553
-
----
-kind: Deployment
-apiVersion: apps/v1
-metadata:
-  name: "${node_label}"
-  labels:
-    app: $node_label
-spec:
-  replicas: 1
-  selector:
-    matchLabels:
-      app: $node_label
-  template:
-    metadata:
-      labels:
-       app:  $node_label
-    spec:
-      containers:
-        - name: $node_label
-
-          image: "${docker_repository}/casper-kube-node"
-          env:
-          - name: CASPER_NODE_GIT_HASH
-            value: "$git_hash"
-          - name: CASPER_NODE_INDEX
-            value: "$zero_pad_index"
-          - name: NETWORK_NAME
-            value: "$network_name"
-          - name: RUST_LOG
-            value: info
-          - name: RUST_BACKTRACE
-            value: "1"
-          resources:
-            limits:
-              cpu: "$node_cpu_limit"
-              memory: "$node_mem_limit"
-            requests:
-              cpu: "$node_cpu_request"
-              memory: "$node_mem_request"
-          volumeMounts:
-          - mountPath: "/storage"
-            name: $node_label-pv
-          securityContext:
-            capabilities:
-              add:
-                - NET_ADMIN
-      volumes:
-        - name: $node_label-pv
-          persistentVolumeClaim:
-            claimName: $node_label-pv-claim
-
-
-EOF
-
-done
-
-cat << EOF >> $kube_resources_yaml
-
----
-kind: Pod
-apiVersion: v1
-metadata:
-  name: casper-util
-spec:
-  containers:
-  - image: "${docker_repository}/casper-kube-util"
-    env:
-    - name: CASPER_NODE_GIT_HASH
-      value: "$git_hash"
-    name: casper-util
-  restartPolicy: Always
-EOF
-
-cat << EOF >> $kube_resources_yaml
-
----
-kind: Pod
-apiVersion: v1
-metadata:
-  name: casper-stests
-spec:
-  containers:
-  - image: "${docker_repository}/casper-kube-stests"
-    env:
-    - name: CASPER_NODE_GIT_HASH
-      value: "$git_hash"
-    - name: NETWORK_NAME
-      value: "$network_name"
-    name: casper-stests
-  restartPolicy: Always
-EOF
+helm install "casper-kube" \
+  --namespace="${network_name}" \
+  --set gitHash="${git_hash}" \
+  --set network_name="${network_name}" \
+  --set replicaCount="${node_count}" \
+  --set volumeClaimSize="${node_storage_capacity}" \
+  --set resources.requests.memory="${node_mem_request}" \
+  --set resources.requests.cpu="${node_cpu_request}" \
+  --set resources.limits.memory="${node_mem_limit}" \
+  --set resources.limits.cpu="${node_cpu_limit}" \
+  --set image.tag="${image_tag}" \
+  ./deploy/casper-kube
 
 ############################################################################################
 # apply Kubernetes Resources
 ############################################################################################
-
-kubectl create namespace $network_name
-kubectl apply -n $network_name -f $kube_resources_yaml
 
 echo ""
 echo "Network creation complete."
